/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.PhongBanDAO;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import pojo.*;
import pojo.PhongBanPOJO;
/**
 *
 * @author Sony
 */
public class Panel2 extends javax.swing.JPanel {

    /**
     * Creates new form PNTrang1
     */
    public Panel2() {
        initComponents();
    }
    public void hiemThiPhongBan(){
        ArrayList<PhongBanPOJO>  ds=PhongBanDAO.layDanhSachPhongBan();
        DefaultTableModel dtm=new  DefaultTableModel();
        dtm.addColumn("MaPhongBan");
        dtm.addColumn("TenPhongBan");
        dtm.setNumRows(ds.size());
        for(int i=0;i<ds.size();i++){
            PhongBanPOJO pb=ds.get(i);
            dtm.setValueAt(pb.maPhongBan, i, 0);
            dtm.setValueAt(pb.tenPhongBan, i, 1);
        }
        // hiem thi nen table
        this.tbPhongBan.setModel(dtm);
        this.tbPhongBan.changeSelection(0,0,false, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbPhongBan = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTenPhongBan = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setPreferredSize(new java.awt.Dimension(1200, 700));

        tbPhongBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbPhongBan);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        txtTenPhongBan.setText("jTextField1");
        txtTenPhongBan.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTenPhongBanCaretUpdate(evt);
            }
        });

        btnTimKiem.setText("Tim kiem");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(448, 448, 448))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
            .addGroup(layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jLabel1)
                .addGap(87, 87, 87)
                .addComponent(txtTenPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnTimKiem)
                .addGap(0, 108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTenPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.hiemThiPhongBan();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        ArrayList<PhongBanPOJO> ds=PhongBanDAO.timPhongBan(txtTenPhongBan.getText());
        DefaultTableModel dtm =new  DefaultTableModel();
        dtm.addColumn("MaPhongBan");
        dtm.addColumn("TenPhongBan");
        dtm.setNumRows(ds.size());
        for(int i=0;i<ds.size();i++){
            PhongBanPOJO pb=ds.get(i);
            dtm.setValueAt(pb.maPhongBan, i, 0);
            dtm.setValueAt(pb.tenPhongBan, i, 1);
        }
        // hiem thi nen table
        this.tbPhongBan.setModel(dtm);
        this.tbPhongBan.repaint();
        this.tbPhongBan.validate();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void txtTenPhongBanCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTenPhongBanCaretUpdate
         ArrayList<PhongBanPOJO> ds=PhongBanDAO.timPhongBan(txtTenPhongBan.getText());
        DefaultTableModel dtm =new  DefaultTableModel();
        dtm.addColumn("MaPhongBan");
        dtm.addColumn("TenPhongBan");
        dtm.setNumRows(ds.size());
        for(int i=0;i<ds.size();i++){
            PhongBanPOJO pb=ds.get(i);
            dtm.setValueAt(pb.maPhongBan, i, 0);
            dtm.setValueAt(pb.tenPhongBan, i, 1);
        }
        // hiem thi nen table
        this.tbPhongBan.setModel(dtm);
        this.tbPhongBan.repaint();
        this.tbPhongBan.validate();
    }//GEN-LAST:event_txtTenPhongBanCaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbPhongBan;
    private javax.swing.JTextField txtTenPhongBan;
    // End of variables declaration//GEN-END:variables
}
