/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlks;

import gui.Panel1;
import javax.swing.JPanel;

/**
 *
 * @author Sony
 */
public class Main_JFrame extends javax.swing.JFrame {

    /**
     * Creates new form Main_JFrame
     */
    private JPanel childPanel;
    public Main_JFrame() {
        initComponents();
        //this.lbTenNguoiDung.setText(Login.manv);
        showPanel(new Panel1());
         
    }
    
    public void showPanel(JPanel panel)
    {
        childPanel=panel;
        pnMain.removeAll();
        pnMain.add(childPanel);
        pnMain.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnpanel1 = new javax.swing.JButton();
        btbpanel2 = new javax.swing.JButton();
        pnMain = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        pn1 = new javax.swing.JMenu();
        pn11 = new javax.swing.JMenuItem();
        pn2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnpanel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnpanel1.setText("Phiếu Thuê Phòng");
        btnpanel1.setFocusable(false);
        btnpanel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnpanel1.setMargin(new java.awt.Insets(2, 20, 2, 30));
        btnpanel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnpanel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpanel1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnpanel1);

        btbpanel2.setText("panel2");
        btbpanel2.setFocusable(false);
        btbpanel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btbpanel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btbpanel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbpanel2ActionPerformed(evt);
            }
        });
        jToolBar1.add(btbpanel2);

        pnMain.setBackground(new java.awt.Color(204, 204, 255));
        pnMain.setLayout(new java.awt.BorderLayout());

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        pn1.setText("File");

        pn11.setText("showpn1");
        pn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pn11ActionPerformed(evt);
            }
        });
        pn1.add(pn11);

        pn2.setText("show pn2");
        pn1.add(pn2);

        jMenuItem3.setText("exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        pn1.add(jMenuItem3);

        jMenuBar1.add(pn1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1396, Short.MAX_VALUE)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pn11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pn11ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnpanel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpanel1ActionPerformed
            showPanel(new Panel1());
    }//GEN-LAST:event_btnpanel1ActionPerformed

    private void btbpanel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbpanel2ActionPerformed
        showPanel(new Panel2());
    }//GEN-LAST:event_btbpanel2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbpanel2;
    private javax.swing.JButton btnpanel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu pn1;
    private javax.swing.JMenuItem pn11;
    private javax.swing.JMenuItem pn2;
    private javax.swing.JPanel pnMain;
    // End of variables declaration//GEN-END:variables
}
